// THIS FILE IS AUTOMATICALLY GENERATED by TecoRegionDataGenerator.
// DO NOT EDIT.

let regions: [Region] = [
    Region(id: "ap-guangzhou", localized: ["South China(Guangzhou)", "华南地区(广州)"]),
    Region(id: "ap-shanghai", localized: ["East China(Shanghai)", "华东地区(上海)"]),
    Region(id: "ap-nanjing", localized: ["East China(Nanjing)", "华东地区(南京)"]),
    Region(id: "ap-hongkong", localized: ["Hong Kong, Macau and Taiwan (China)(Hong Kong, China)", "港澳台地区(中国香港)"]),
    Region(id: "na-toronto", localized: ["North America(Toronto)", "北美地区(多伦多)"]),
    Region(id: "ap-beijing", localized: ["North China region(Beijing)", "华北地区(北京)"]),
    Region(id: "ap-singapore", localized: ["Southeast Asia(Singapore)", "亚太东南(新加坡)"]),
    Region(id: "ap-bangkok", localized: ["Southeast Asia(Bangkok)", "亚太东南(曼谷)"]),
    Region(id: "ap-jakarta", localized: ["Southeast Asia(Jakarta)", "亚太东南(雅加达)"]),
    Region(id: "na-siliconvalley", localized: ["US West(Silicon Valley)", "美国西部(硅谷)"]),
    Region(id: "ap-chengdu", localized: ["Southwest China(Chengdu)", "西南地区(成都)"]),
    Region(id: "ap-chongqing", localized: ["Southwest China(Chongqing)", "西南地区(重庆)"]),
    Region(id: "eu-frankfurt", localized: ["Europe(Frankfurt)", "欧洲地区(法兰克福)"]),
    Region(id: "eu-moscow", localized: ["Europe(Northeastern Europe)", "欧洲地区(莫斯科)"]),
    Region(id: "ap-seoul", localized: ["Northeast Asia(Seoul)", "亚太东北(首尔)"]),
    Region(id: "ap-tokyo", localized: ["Northeast Asia(Tokyo)", "亚太东北(东京)"]),
    Region(id: "ap-mumbai", localized: ["South Asia(Mumbai)", "亚太南部(孟买)"]),
    Region(id: "na-ashburn", localized: ["US East(Virginia)", "美国东部(弗吉尼亚)"]),
    Region(id: "sa-saopaulo", localized: ["South America(São Paulo)", "南美地区(圣保罗)"]),
]
