// THIS FILE IS AUTOMATICALLY GENERATED by TecoRegionDataGenerator.
// DO NOT EDIT.

struct Region: Hashable {
    let id: String

    let localizedNames: [String]
}

let regions = [
    Region(id: "ap-guangzhou", localizedNames: ["South China(Guangzhou)", "华南地区(广州)"]),
    Region(id: "ap-shanghai", localizedNames: ["East China(Shanghai)", "华东地区(上海)"]),
    Region(id: "ap-nanjing", localizedNames: ["East China(Nanjing)", "华东地区(南京)"]),
    Region(id: "ap-hongkong", localizedNames: ["Hong Kong, Macau and Taiwan (China)(Hong Kong, China)", "港澳台地区(中国香港)"]),
    Region(id: "na-toronto", localizedNames: ["North America(Toronto)", "北美地区(多伦多)"]),
    Region(id: "ap-beijing", localizedNames: ["North China region(Beijing)", "华北地区(北京)"]),
    Region(id: "ap-singapore", localizedNames: ["Southeast Asia(Singapore)", "亚太东南(新加坡)"]),
    Region(id: "ap-bangkok", localizedNames: ["Southeast Asia(Bangkok)", "亚太东南(曼谷)"]),
    Region(id: "ap-jakarta", localizedNames: ["Southeast Asia(Jakarta)", "亚太东南(雅加达)"]),
    Region(id: "na-siliconvalley", localizedNames: ["US West(Silicon Valley)", "美国西部(硅谷)"]),
    Region(id: "ap-chengdu", localizedNames: ["Southwest China(Chengdu)", "西南地区(成都)"]),
    Region(id: "ap-chongqing", localizedNames: ["Southwest China(Chongqing)", "西南地区(重庆)"]),
    Region(id: "eu-frankfurt", localizedNames: ["Europe(Frankfurt)", "欧洲地区(法兰克福)"]),
    Region(id: "eu-moscow", localizedNames: ["Europe(Northeastern Europe)", "欧洲地区(莫斯科)"]),
    Region(id: "ap-seoul", localizedNames: ["Northeast Asia(Seoul)", "亚太东北(首尔)"]),
    Region(id: "ap-tokyo", localizedNames: ["Northeast Asia(Tokyo)", "亚太东北(东京)"]),
    Region(id: "ap-mumbai", localizedNames: ["South Asia(Mumbai)", "亚太南部(孟买)"]),
    Region(id: "na-ashburn", localizedNames: ["US East(Virginia)", "美国东部(弗吉尼亚)"]),
    Region(id: "sa-saopaulo", localizedNames: ["South America(São Paulo)", "南美地区(圣保罗)"]),
]
