name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.7'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -c ${{ matrix.build-config }}
