name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -c ${{ matrix.build-config }}
      - name: Save build cache
        uses: actions/cache/save@v3
        if: ${{ matrix.build-config == 'release' }}
        with:
          path: .build
          key: ${{ runner.os }}-${{ github.sha }}
